#!/usr/bin/env bash
# brainspike installer
#
# Discovers available memory layers, generates a tailored UserPromptSubmit
# hook at ~/.claude/hooks/brainspike.sh, and registers it in the project's
# .claude/settings.local.json.
#
# Usage:
#   ./install.sh                # probe and install
#   ./install.sh --dry-run      # probe and print plan, do not write anything
#   ./install.sh --hook <path>  # write hook to a custom path
#   ./install.sh --pretool-hook <path>
#   ./install.sh --settings <path>
#   ./install.sh --probes <dir>
#   ./install.sh --no-register  # skip settings.local.json update
#   ./install.sh --global       # register in ~/.claude/settings.json instead

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROBES_DIR="$SCRIPT_DIR/probes"
HOOK_FILE="$HOME/.claude/hooks/brainspike.sh"
PRETOOL_HOOK_FILE="$HOME/.claude/hooks/brainspike-pretool.sh"
SETTINGS_FILE=".claude/settings.local.json"
DRY_RUN=0
DO_REGISTER=1

while [ $# -gt 0 ]; do
    case "$1" in
        --dry-run) DRY_RUN=1; shift ;;
        --hook) HOOK_FILE="$2"; shift 2 ;;
        --pretool-hook) PRETOOL_HOOK_FILE="$2"; shift 2 ;;
        --settings) SETTINGS_FILE="$2"; shift 2 ;;
        --probes) PROBES_DIR="$2"; shift 2 ;;
        --no-register) DO_REGISTER=0; shift ;;
        --global) SETTINGS_FILE="$HOME/.claude/settings.json"; shift ;;
        -h|--help)
            sed -n '2,15p' "$0" | sed 's/^# \{0,1\}//'
            exit 0 ;;
        *) echo "unknown arg: $1" >&2; exit 2 ;;
    esac
done

if ! command -v jq >/dev/null 2>&1; then
    echo "jq is required (apt install jq / brew install jq)" >&2
    exit 1
fi

if [ ! -d "$PROBES_DIR" ]; then
    echo "probes directory not found: $PROBES_DIR" >&2
    exit 1
fi

echo "==> Discovering memory layers in: $PWD"

active=()
active_files=()

for probe_file in "$PROBES_DIR"/*.sh; do
    [ -f "$probe_file" ] || continue
    name="$(basename "$probe_file" .sh)"
    if (
        set +e
        # shellcheck disable=SC1090
        source "$probe_file"
        probe_detect >/dev/null 2>&1 || exit 1
        probe_test_query >/dev/null 2>&1 || exit 1
        exit 0
    ); then
        echo "  [ok]    $name"
        active+=("$name")
        active_files+=("$probe_file")
    else
        echo "  [skip]  $name (not detected or test query failed)"
    fi
done

if [ ${#active[@]} -eq 0 ]; then
    echo
    echo "No memory layers detected. The hook will still be installed but will"
    echo "only emit a structural reminder. Add probes under $PROBES_DIR and rerun."
fi

# --- generate hook ---------------------------------------------------------
tmp_hook="$(mktemp)"
tmp_pretool_hook="$(mktemp)"
trap 'rm -f "$tmp_hook" "$tmp_pretool_hook"' EXIT

# Helper functions emitted verbatim into both generated hooks.
emit_shared_helpers() {
    cat <<'BS_HELPERS'
brainspike_session_file() {
    local sid safe base
    sid="${SESSION_ID:-unknown}"
    safe="$(printf '%s' "$sid" | tr -c 'A-Za-z0-9_.-' '_')"
    base="${TMPDIR:-/tmp}/brainspike"
    mkdir -p "$base" 2>/dev/null || return 1
    printf '%s/%s.surfaced\n' "$base" "$safe"
}

brainspike_key() {
    local layer="$1" line="$2"
    printf '%s\0%s' "$layer" "$line" | cksum | awk '{print $1 "-" $2}'
}
BS_HELPERS
}

{
    echo '#!/usr/bin/env bash'
    echo '# brainspike UserPromptSubmit hook'
    echo '# Generated by brainspike installer on '"$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo '# Active layers: '"${active[*]:-none}"
    echo 'set -uo pipefail'
    echo
    echo 'HOOK_INPUT="$(cat 2>/dev/null || true)"'
    echo 'PROMPT="$(printf '"'"'%s'"'"' "$HOOK_INPUT" | jq -r ".prompt // empty" 2>/dev/null || true)"'
    echo 'SESSION_ID="$(printf '"'"'%s'"'"' "$HOOK_INPUT" | jq -r ".session_id // \"unknown\"" 2>/dev/null || echo unknown)"'
    echo 'if [ -z "${PROMPT:-}" ] || [ "${PROMPT}" = "null" ]; then exit 0; fi'
    echo
    emit_shared_helpers
    echo
    echo 'brainspike_seen() {'
    echo '    local layer="$1" line="$2" state key'
    echo '    state="$(brainspike_session_file)" || return 1'
    echo '    key="${layer}:$(brainspike_key "$layer" "$line")"'
    echo '    grep -Fxq "$key" "$state" 2>/dev/null'
    echo '}'
    echo
    echo 'brainspike_mark_surfaced() {'
    echo '    local layer="$1" line="$2" state key'
    echo '    state="$(brainspike_session_file)" || return 0'
    echo '    key="${layer}:$(brainspike_key "$layer" "$line")"'
    echo '    grep -Fxq "$key" "$state" 2>/dev/null && return 0'
    echo '    printf '"'"'%s\n'"'"' "$key" >> "$state" 2>/dev/null || true'
    echo '}'
    echo
    echo 'BRAINSPIKE_TMP="$(mktemp -d 2>/dev/null || mktemp -d -t brainspike)"'
    echo 'trap '"'"'rm -rf "$BRAINSPIKE_TMP"'"'"' EXIT'
    echo
    echo 'ANY_RESULTS=0'
    echo
    echo '# --- registry of active layers (for breadcrumbs / fallback) ---'
    echo 'BRAINSPIKE_LAYERS=('
    for n in "${active[@]}"; do
        printf '    %q\n' "$n"
    done
    echo ')'
    echo
    echo 'declare -A BRAINSPIKE_BREADCRUMBS=()'
    echo 'declare -A BRAINSPIKE_DESCRIPTIONS=()'
    echo

    # Per-layer breadcrumb / description registration
    for i in "${!active[@]}"; do
        f="${active_files[$i]}"
        echo "(  # capture breadcrumb + description for '${active[$i]}'"
        echo "    set +u"
        cat "$f"
        echo "    bc=\"\$(probe_breadcrumb 2>/dev/null || true)\""
        echo "    desc=\"\${PROBE_DESCRIPTION:-}\""
        echo "    printf '%s\\0%s\\0' \"\$bc\" \"\$desc\" > \"\$BRAINSPIKE_TMP/${active[$i]}.meta\""
        echo ")"
        echo "if [ -s \"\$BRAINSPIKE_TMP/${active[$i]}.meta\" ]; then"
        echo "    bc=\"\$(awk 'BEGIN{RS=\"\\0\"} NR==1' \"\$BRAINSPIKE_TMP/${active[$i]}.meta\")\""
        echo "    desc=\"\$(awk 'BEGIN{RS=\"\\0\"} NR==2' \"\$BRAINSPIKE_TMP/${active[$i]}.meta\")\""
        echo "    BRAINSPIKE_BREADCRUMBS[${active[$i]}]=\"\$bc\""
        echo "    BRAINSPIKE_DESCRIPTIONS[${active[$i]}]=\"\$desc\""
        echo "fi"
        echo
    done

    echo 'OUT_FILE="$BRAINSPIKE_TMP/output"'
    echo ': > "$OUT_FILE"'
    echo

    # Per-layer query
    for i in "${!active[@]}"; do
        f="${active_files[$i]}"
        n="${active[$i]}"
        echo "# === probe: $n ==="
        echo "("
        echo "    set +u"
        cat "$f"
        echo "    output=\"\$(probe_query \"\$PROMPT\" 2>/dev/null || true)\""
        echo "    bc=\"\${BRAINSPIKE_BREADCRUMBS[$n]:-\$(probe_breadcrumb 2>/dev/null)}\""
        echo "    # Across-turn dedup: only surface breadcrumbs not already shown this session."
        echo "    novel=\"\$BRAINSPIKE_TMP/$n.novel\""
        echo "    : > \"\$novel\""
        echo "    while IFS= read -r line; do"
        echo "        [ -n \"\$line\" ] || continue"
        echo "        if ! brainspike_seen \"$n\" \"\$line\"; then"
        echo "            printf '%s\\n' \"\$line\" >> \"\$novel\""
        echo "            brainspike_mark_surfaced \"$n\" \"\$line\""
        echo "        fi"
        echo "    done <<< \"\$output\""
        echo "    if [ -s \"\$novel\" ]; then"
        echo "        count=\$(grep -c '^' \"\$novel\" 2>/dev/null || echo 0)"
        echo "        printf '%s (%d match%s, run \`%s\` for more):\\n' \"$n\" \"\$count\" \"\$( [ \"\$count\" -eq 1 ] || echo 'es' )\" \"\$bc\" >> \"\$OUT_FILE\""
        echo "        cat \"\$novel\" >> \"\$OUT_FILE\""
        echo "        printf '\\n' >> \"\$OUT_FILE\""
        echo "        echo 1 > \"\$BRAINSPIKE_TMP/$n.hit\""
        echo "    else"
        echo "        printf '%s: no matches\\n\\n' \"$n\" >> \"\$OUT_FILE\""
        echo "    fi"
        echo ") &"
        echo
    done

    echo '# Wait up to ~9s for all probes (each probe internally caps at 3s)'
    echo 'PROBE_DEADLINE=$(( $(date +%s) + 9 ))'
    echo 'while [ "$(jobs -rp | wc -l)" -gt 0 ]; do'
    echo '    [ "$(date +%s)" -ge "$PROBE_DEADLINE" ] && { jobs -p | xargs -r kill 2>/dev/null; break; }'
    echo '    sleep 0.2'
    echo 'done'
    echo 'wait 2>/dev/null || true'
    echo
    echo 'for f in "$BRAINSPIKE_TMP"/*.hit; do'
    echo '    [ -f "$f" ] && ANY_RESULTS=1'
    echo 'done'
    echo
    echo 'echo "=== brainspike ==="'
    echo 'if [ "$ANY_RESULTS" = "1" ]; then'
    echo '    cat "$OUT_FILE"'
    echo 'else'
    echo '    if [ ${#BRAINSPIKE_LAYERS[@]} -eq 0 ]; then'
    echo '        echo "(no memory layers configured at install time)"'
    echo '    else'
    echo '        echo "No matches in any layer. Available layers:"'
    echo '        for layer in "${BRAINSPIKE_LAYERS[@]}"; do'
    echo '            bc="${BRAINSPIKE_BREADCRUMBS[$layer]:-(see layer docs)}"'
    echo '            desc="${BRAINSPIKE_DESCRIPTIONS[$layer]:-}"'
    echo '            if [ -n "$desc" ]; then'
    echo '                printf "  - %s — %s\n      %s\n" "$layer" "$desc" "$bc"'
    echo '            else'
    echo '                printf "  - %s\n      %s\n" "$layer" "$bc"'
    echo '            fi'
    echo '        done'
    echo '    fi'
    echo 'fi'
    echo 'echo'
    echo 'echo "Consult these before asking the user for context you could find yourself."'
    echo 'echo "Top results shown per layer (capped, repeats suppressed) — use the commands above for deeper searches."'
    echo 'echo "=== end brainspike ==="'
    echo 'exit 0'
} > "$tmp_hook"

{
    echo '#!/usr/bin/env bash'
    echo '# brainspike PreToolUse hook'
    echo '# Generated by brainspike installer on '"$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo '# Active layers: '"${active[*]:-none}"
    echo 'set -uo pipefail'
    echo
    echo '[ "${BRAINSPIKE_PRETOOL:-1}" = "0" ] && exit 0'
    echo 'START_MS="$(date +%s%3N 2>/dev/null || date +%s000)"'
    echo 'HOOK_INPUT="$(cat 2>/dev/null || true)"'
    echo 'SESSION_ID="$(printf '"'"'%s'"'"' "$HOOK_INPUT" | jq -r ".session_id // \"unknown\"" 2>/dev/null || echo unknown)"'
    echo 'TOOL_NAME="$(printf '"'"'%s'"'"' "$HOOK_INPUT" | jq -r ".tool_name // empty" 2>/dev/null || true)"'
    echo
    echo 'case "$TOOL_NAME" in'
    echo '    Grep|Glob) QUERY="$(printf '"'"'%s'"'"' "$HOOK_INPUT" | jq -r ".tool_input.pattern // empty" 2>/dev/null || true)" ;;'
    echo '    Task|Agent) QUERY="$(printf '"'"'%s'"'"' "$HOOK_INPUT" | jq -r ".tool_input.prompt // empty" 2>/dev/null || true)" ;;'
    echo '    WebSearch) QUERY="$(printf '"'"'%s'"'"' "$HOOK_INPUT" | jq -r ".tool_input.query // empty" 2>/dev/null || true)" ;;'
    echo '    WebFetch) QUERY="$(printf '"'"'%s'"'"' "$HOOK_INPUT" | jq -r '"'"'[.tool_input.url // empty, .tool_input.prompt // empty] | map(select(. != "")) | join(" ")'"'"' 2>/dev/null || true)" ;;'
    echo '    *) exit 0 ;;'
    echo 'esac'
    echo '[ -z "${QUERY:-}" ] || [ "${QUERY}" = "null" ] && exit 0'
    echo
    emit_shared_helpers
    echo
    echo 'brainspike_seen() {'
    echo '    local layer="$1" line="$2" state key'
    echo '    state="$(brainspike_session_file)" || return 1'
    echo '    key="${layer}:$(brainspike_key "$layer" "$line")"'
    echo '    grep -Fxq "$key" "$state" 2>/dev/null'
    echo '}'
    echo
    echo 'brainspike_mark_surfaced() {'
    echo '    local layer="$1" line="$2" state key'
    echo '    state="$(brainspike_session_file)" || return 0'
    echo '    key="${layer}:$(brainspike_key "$layer" "$line")"'
    echo '    grep -Fxq "$key" "$state" 2>/dev/null && return 0'
    echo '    printf '"'"'%s\n'"'"' "$key" >> "$state" 2>/dev/null || true'
    echo '    printf '"'"'%s\n'"'"' "$key" >> "$BRAINSPIKE_TMP/keys" 2>/dev/null || true'
    echo '}'
    echo
    echo 'BRAINSPIKE_TMP="$(mktemp -d 2>/dev/null || mktemp -d -t brainspike-pretool)"'
    echo 'trap '"'"'rm -rf "$BRAINSPIKE_TMP"'"'"' EXIT'
    echo 'OUT_FILE="$BRAINSPIKE_TMP/output"'
    echo ': > "$OUT_FILE"'
    echo ': > "$BRAINSPIKE_TMP/keys"'
    echo 'BRAINSPIKE_PROBE_TIMEOUT="${BRAINSPIKE_PROBE_TIMEOUT:-1.5}"'
    echo
    for i in "${!active[@]}"; do
        f="${active_files[$i]}"
        n="${active[$i]}"
        echo "# === probe: $n ==="
        echo "("
        echo "    set +u"
        cat "$f"
        echo "    probe_out=\"\$BRAINSPIKE_TMP/$n.raw\""
        echo "    : > \"\$probe_out\""
        echo "    ( probe_query \"\$QUERY\" > \"\$probe_out\" 2>/dev/null ) &"
        echo "    probe_pid=\$!"
        echo "    ( sleep \"\$BRAINSPIKE_PROBE_TIMEOUT\"; kill \"\$probe_pid\" 2>/dev/null || true ) &"
        echo "    killer_pid=\$!"
        echo "    wait \"\$probe_pid\" 2>/dev/null || true"
        echo "    kill \"\$killer_pid\" 2>/dev/null || true"
        echo "    wait \"\$killer_pid\" 2>/dev/null || true"
        echo "    novel=\"\$BRAINSPIKE_TMP/$n.novel\""
        echo "    : > \"\$novel\""
        echo "    while IFS= read -r line; do"
        echo "        [ -n \"\$line\" ] || continue"
        echo "        if ! brainspike_seen \"$n\" \"\$line\"; then"
        echo "            printf '%s\\n' \"\$line\" >> \"\$novel\""
        echo "            brainspike_mark_surfaced \"$n\" \"\$line\""
        echo "        fi"
        echo "    done < \"\$probe_out\""
        echo "    if [ -s \"\$novel\" ]; then"
        echo "        count=\$(grep -c '^' \"\$novel\" 2>/dev/null || echo 0)"
        echo "        bc=\"\$(probe_breadcrumb 2>/dev/null || true)\""
        echo "        printf '%s (%d match%s, run \`%s\` for more):\\n' \"$n\" \"\$count\" \"\$( [ \"\$count\" -eq 1 ] || echo 'es' )\" \"\$bc\" >> \"\$OUT_FILE\""
        echo "        cat \"\$novel\" >> \"\$OUT_FILE\""
        echo "        printf '\\n' >> \"\$OUT_FILE\""
        echo "        echo 1 > \"\$BRAINSPIKE_TMP/$n.hit\""
        echo "    fi"
        echo ") &"
        echo
    done
    echo 'PROBE_DEADLINE=$(( $(date +%s) + 3 ))'
    echo 'while [ "$(jobs -rp | wc -l)" -gt 0 ]; do'
    echo '    [ "$(date +%s)" -ge "$PROBE_DEADLINE" ] && { jobs -p | xargs -r kill 2>/dev/null; break; }'
    echo '    sleep 0.1'
    echo 'done'
    echo 'wait 2>/dev/null || true'
    echo
    echo 'ANY_RESULTS=0'
    echo 'for f in "$BRAINSPIKE_TMP"/*.hit; do'
    echo '    [ -f "$f" ] && ANY_RESULTS=1'
    echo 'done'
    echo '[ "$ANY_RESULTS" = "1" ] || exit 0'
    echo
    echo 'CTX_FILE="$BRAINSPIKE_TMP/context"'
    echo '{'
    echo '    echo "=== brainspike (mid-turn) ==="'
    echo '    cat "$OUT_FILE"'
    echo '    echo "Consult these before continuing if they look relevant."'
    echo '    echo "=== end brainspike ==="'
    echo '} > "$CTX_FILE"'
    echo 'END_MS="$(date +%s%3N 2>/dev/null || date +%s000)"'
    echo 'DURATION_MS=$(( END_MS - START_MS ))'
    echo 'mkdir -p "$HOME/.claude" 2>/dev/null || true'
    echo 'keys="$(paste -sd "," "$BRAINSPIKE_TMP/keys" 2>/dev/null || true)"'
    echo 'jq -cn --arg session "$SESSION_ID" --arg tool "$TOOL_NAME" --arg query "$QUERY" --arg keys "$keys" --argjson durationMs "$DURATION_MS" '"'"'{session:$session,tool:$tool,query:$query,keys:($keys|split(",")|map(select(. != ""))),durationMs:$durationMs}'"'"' >> "$HOME/.claude/brainspike-pretool.log" 2>/dev/null || true'
    echo 'jq -n --arg ctx "$(cat "$CTX_FILE")" '"'"'{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"allow",additionalContext:$ctx}}'"'"''
    echo 'exit 0'
} > "$tmp_pretool_hook"

if [ "$DRY_RUN" = "1" ]; then
    echo
    echo "==> Dry run. Would write hook to: $HOOK_FILE"
    echo "    Lines: $(wc -l < "$tmp_hook")"
    echo "    First 30 lines:"
    sed -n '1,30p' "$tmp_hook" | sed 's/^/      /'
    echo
    echo "==> Would write PreToolUse hook to: $PRETOOL_HOOK_FILE"
    echo "    Lines: $(wc -l < "$tmp_pretool_hook")"
    echo "    First 30 lines:"
    sed -n '1,30p' "$tmp_pretool_hook" | sed 's/^/      /'
    if [ "$DO_REGISTER" = "1" ]; then
        echo
        echo "==> Would register in: $SETTINGS_FILE"
    fi
    exit 0
fi

mkdir -p "$(dirname "$HOOK_FILE")"
mv "$tmp_hook" "$HOOK_FILE"
chmod +x "$HOOK_FILE"
echo
echo "==> Wrote hook: $HOOK_FILE"

mkdir -p "$(dirname "$PRETOOL_HOOK_FILE")"
mv "$tmp_pretool_hook" "$PRETOOL_HOOK_FILE"
trap - EXIT
chmod +x "$PRETOOL_HOOK_FILE"
echo "==> Wrote PreToolUse hook: $PRETOOL_HOOK_FILE"

# --- register in settings ---------------------------------------------------
if [ "$DO_REGISTER" = "1" ]; then
    mkdir -p "$(dirname "$SETTINGS_FILE")"
    if [ ! -f "$SETTINGS_FILE" ]; then
        echo '{}' > "$SETTINGS_FILE"
    fi

    # Ensure file is valid JSON; if not, refuse to clobber
    if ! jq empty "$SETTINGS_FILE" 2>/dev/null; then
        echo "==> Existing $SETTINGS_FILE is not valid JSON. Skipping registration."
        echo "    Add this manually under hooks.UserPromptSubmit:"
        echo "      { \"hooks\": [{ \"type\": \"command\", \"command\": \"$HOOK_FILE\" }] }"
        echo "    And under hooks.PreToolUse:"
        echo "      { \"matcher\": \"Grep|Glob|Task|Agent|WebSearch|WebFetch\", \"hooks\": [{ \"type\": \"command\", \"command\": \"$PRETOOL_HOOK_FILE\" }] }"
    else
        tmp_settings="$(mktemp)"
        HOOK_PATH="$HOOK_FILE" PRETOOL_HOOK_PATH="$PRETOOL_HOOK_FILE" jq '
            .hooks //= {} |
            .hooks.UserPromptSubmit //= [] |
            .hooks.PreToolUse //= [] |
            if any(.hooks.UserPromptSubmit[]?.hooks[]?; .command == env.HOOK_PATH)
            then .
            else .hooks.UserPromptSubmit += [{
                "hooks": [{ "type": "command", "command": env.HOOK_PATH }]
            }]
            end |
            if any(.hooks.PreToolUse[]?.hooks[]?; .command == env.PRETOOL_HOOK_PATH)
            then .
            else .hooks.PreToolUse += [{
                "matcher": "Grep|Glob|Task|Agent|WebSearch|WebFetch",
                "hooks": [{ "type": "command", "command": env.PRETOOL_HOOK_PATH }]
            }]
            end
        ' "$SETTINGS_FILE" > "$tmp_settings"

        if jq empty "$tmp_settings" 2>/dev/null; then
            mv "$tmp_settings" "$SETTINGS_FILE"
            echo "==> Registered in: $SETTINGS_FILE"
        else
            rm -f "$tmp_settings"
            echo "==> Failed to update $SETTINGS_FILE. Add the hook manually."
            exit 1
        fi
    fi
fi

echo
echo "Active layers: ${active[*]:-none}"
echo "Done. The hooks will fire on the next UserPromptSubmit and eligible PreToolUse in this project."
